// Automatically generated by astro-icon
// 9ca74dd73425b07eedc7348b0b5ee103e45514054e5347b5b79b378b47266115

declare module 'virtual:astro-icon' {
	export type Icon = 
		| "breadcrumb/home"
		| "delete"
		| "home"
		| "inbox/inbox"
		| "shared/add"
		| "shared/agreement"
		| "shared/arrow-up-right"
		| "shared/call"
		| "shared/check_circle"
		| "shared/chevron-down"
		| "shared/chevron-right"
		| "shared/chevron-up"
		| "shared/circledArrow"
		| "shared/close"
		| "shared/ellipsis-vertical"
		| "shared/error"
		| "shared/exclamation_sign"
		| "shared/login"
		| "shared/menu"
		| "shared/minus"
		| "shared/notification"
		| "shared/pencil"
		| "shared/plus"
		| "shared/projects"
		| "shared/report"
		| "shared/search"
		| "shared/setting"
		| "shared/template"
		| "shared/type"
		| "shared/upload"
		| "user/user";
}