// Automatically generated by astro-icon
<<<<<<< HEAD
// a63bea193aad870fbab608ccecc209164654de640875c85904a3c9d68f7d26d0
=======
// a0b6a878e6110e686937a37d48aaad155dbaf93f0a291abb695d6e172ed5c30e
>>>>>>> 3f89fbc1fdab80d6936e7109348911f14f1d23a6

declare module 'virtual:astro-icon' {
	export type Icon = 
		| "breadcrumb/home"
		| "delete"
		| "home"
		| "inbox/inbox"
		| "shared/add"
		| "shared/arrow-up-right"
		| "shared/check_circle"
		| "shared/chevron-down"
		| "shared/chevron-right"
		| "shared/chevron-up"
		| "shared/close"
		| "shared/ellipsis-vertical"
		| "shared/error"
		| "shared/exclamation_sign"
		| "shared/login"
		| "shared/menu"
		| "shared/minus"
		| "shared/notification"
		| "shared/pencil"
		| "shared/plus"
		| "shared/search"
		| "shared/setting"
		| "shared/setting/tenant01"
		| "shared/setting/tenant02"
		| "shared/template"
		| "shared/type"
		| "shared/upload";
}