// Automatically generated by astro-icon
// 91cdcd4332ffd8b262c4ae5c606824102683526086f02b887de7b85d403172b8

declare module 'virtual:astro-icon' {
	export type Icon = 
		| "breadcrumb/home"
		| "delete"
		| "home"
		| "inbox/inbox"
		| "shared/add"
		| "shared/arrow-up-right"
		| "shared/check_circle"
		| "shared/chevron-down"
		| "shared/chevron-right"
		| "shared/chevron-up"
		| "shared/circledArrow"
		| "shared/close"
		| "shared/ellipsis-vertical"
		| "shared/error"
		| "shared/exclamation_sign"
		| "shared/login"
		| "shared/menu"
		| "shared/minus"
		| "shared/notification"
		| "shared/pencil"
		| "shared/plus"
		| "shared/search"
		| "shared/setting"
		| "shared/template"
		| "shared/type"
		| "shared/upload"
		| "user/user";
}